BooksWebProject/Areas/Admin/Controllers/AccountsController.cs
using BooksWebProject.Resource;
using Domain.Constants;
using Domin.Entity;
using Infarstuructre.Data;
using Infarstuructre.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace WebBook.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Permissions.Accounts.View)]
    public class AccountsController : Controller
    {
        #region Decleration
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly FreeBookDbContext _context;
        #endregion

        #region Constructor
        public AccountsController(RoleManager<IdentityRole> roleManager
            , UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager,
            FreeBookDbContext context)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }
        #endregion

        #region Method
        [Authorize(Permissions.Roles.View)]
        public IActionResult Roles()
        {
            var viewMod = new RolesViewModel()
            {
                NewRole = new NewRole(),
                Roles = _roleManager.Roles.OrderBy(x => x.Name).ToList()
            };
            return View(viewMod);
        }
        [Authorize(Permissions.Roles.Delete)]
        public async Task<IActionResult> DeleteRole(string id)
        {
            var ruselt = _roleManager.Roles.FirstOrDefault(x => x.Id == id);
            if (ruselt != null)
            {
                if((await _roleManager.DeleteAsync(ruselt)).Succeeded)
                {
                    return RedirectToAction("Roles");
                }    
            }
            return RedirectToAction("Roles");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Permissions.Roles.Create)]
        public async Task<IActionResult> Roles(RolesViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = new IdentityRole
                {
                    Id = model.NewRole.RoleId,
                    Name = model.NewRole.RoleName
                };
                //create
                if (role.Id == null)
                {
                    role.Id = Guid.NewGuid().ToString();
                    var result =await _roleManager.CreateAsync(role);
                    if (result.Succeeded)// Succeeded
                        SessionMsg(Helper.Success, ResourceWeb.lbSave,ResourceWeb.lbSaveMsgRole);
                    SessionMsg(Helper.Error, ResourceWeb.lbNotSaved, ResourceWeb.lbNotSavedMsgRole);
                }
                //update
                else
                {
                    var RoleUpdate=await _roleManager.FindByIdAsync(role.Id);
                    RoleUpdate.Id = model.NewRole.RoleId;
                    RoleUpdate.Name = model.NewRole.RoleName;
                    var result = await _roleManager.UpdateAsync(RoleUpdate);
                    if (result.Succeeded)
                        SessionMsg(Helper.Success, ResourceWeb.lbUpdate, ResourceWeb.lbNotUpdateMsgRole);
                     SessionMsg(Helper.Error, ResourceWeb.lbNotUpdate, ResourceWeb.lbNotUpdateMsgRole);   
                }

            }
            return RedirectToAction(nameof(Roles));
        }

        private void SessionMsg(string Type,string Title,string Msg)
        {
            HttpContext.Session.SetString(Helper.MsgType, Type);
            HttpContext.Session.SetString(Helper.Title, Title);
            HttpContext.Session.SetString(Helper.Msg, Msg);
        }
        //public IActionResult Register()
        //{
        //    var model = new RegisterViewModel
        //    //Users = _userManager.Users.in.OrderBy(x => x.Name).ToList() ;
        //    {// VwUsers is being in context if it's not existing in it then would go error
        //     // and also it's must be the same datatype 
        //        Users = _context.VwUsers.OrderBy(x => x.Role).ToList(),//Users in obj model from RegisterViewModel class ..Users has the same datatype as VwUsers in context which is class model VwUser.cs// هاي لست اليوزرس
        //        NewRegister =new NewRegister(),// الفورمة
        //        Roles = _roleManager.Roles.OrderBy(x=>x.Name).ToList(),// عشان الدروب داةن ليست في الفورمة 
        //    };
        //    return View(model);
        //}

        [Authorize(Permissions.Accounts.View)]
        public IActionResult Register()
        {
            var model = new RegisterViewModel
            {
                NewRegister = new NewRegister(),
                Roles = _roleManager.Roles.OrderBy(x => x.Name).ToList(),
                Users = _context.VwUsers.OrderBy(x => x.Role).ToList() //_userManager.Users.OrderBy(x=>x.Name).ToList()
            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Permissions.Accounts.Create)]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var file = HttpContext.Request.Form.Files;
                if (file.Count() > 0)
                {
                    string ImageName = Guid.NewGuid().ToString() + Path.GetExtension(file[0].FileName);
                    var fileStream = new FileStream(Path.Combine(@"wwwroot/", Helper.PathSaveImageuser, ImageName), FileMode.Create);
                    file[0].CopyTo(fileStream);
                    model.NewRegister.ImageUser = ImageName;
                }
                else
                {
                    model.NewRegister.ImageUser = model.NewRegister.ImageUser;
                }
                var user = new ApplicationUser
                {
                    Id=model.NewRegister.Id,
                    Name=model.NewRegister.Name,    
                    Email=model.NewRegister.Email,
                    UserName=model.NewRegister.Email,
                    ImageUser=model.NewRegister.ImageUser,
                    ActiveUser=model.NewRegister.ActiveUser,
                    
                };
                if (user.Id==null)
                {
                    //CREATE
                    user.Id = Guid.NewGuid().ToString();
                    var result = await _userManager.CreateAsync(user, model.NewRegister.Password);
                    if (result.Succeeded)// السكسيدد مش هتنعمل غير تتعمل اويت
                    {
                        ///seccessed  
                        ///
                        var Role = await _userManager.AddToRoleAsync(user, model.NewRegister.RoleName);
                        if (Role.Succeeded)
                        {

                            // Succeeded
                            HttpContext.Session.SetString("msgType", "seccess");
                            HttpContext.Session.SetString("msgTitle", ResourceWeb.lbSave);
                            HttpContext.Session.SetString("msg", ResourceWeb.lbSaveMsgUser);
                        }
                        else
                        {
                            HttpContext.Session.SetString("msgType", "error");
                            HttpContext.Session.SetString("msgTitle", ResourceWeb.lbNotSaved);
                            HttpContext.Session.SetString("msg", ResourceWeb.lbNotSavedMsgRole);
                        }

                    }
                    else
                    {
                        //not secceseedd
                    }
                }
                else
                {
                    //update
                    var userUpdate =await _userManager.FindByIdAsync(model.NewRegister.Id);
                    userUpdate.Id = model.NewRegister.Id;
                    userUpdate.Name = model.NewRegister.Name;
                    userUpdate.Email = model.NewRegister.Email;
                    userUpdate.UserName = model.NewRegister.Email;
                    userUpdate.ImageUser = model.NewRegister.ImageUser; 
                    userUpdate.ActiveUser = model.NewRegister.ActiveUser;
                    var result =await _userManager.UpdateAsync(userUpdate);
                    if (result.Succeeded)
                    {
                        //seeccedd update
                        var oldRole = await _userManager.GetRolesAsync(userUpdate);
                        await _userManager.RemoveFromRolesAsync(userUpdate, oldRole);
                      var AddRole=  await _userManager.AddToRoleAsync(userUpdate,model.NewRegister.RoleName);
                        if (AddRole.Succeeded)
                        {
                            HttpContext.Session.SetString("msgType", "seccess");
                            HttpContext.Session.SetString("msgTitle", ResourceWeb.lbUpdate);
                            HttpContext.Session.SetString("msg", ResourceWeb.lbUpdateMsgUser);
                        }
                        else
                        {
                            HttpContext.Session.SetString("msgType", "error");
                            HttpContext.Session.SetString("msgTitle", ResourceWeb.lbNotUpdate);
                            HttpContext.Session.SetString("msg", ResourceWeb.lbNotUpdateMsgRole);
                        }
                    }
                    else
                    {
                        HttpContext.Session.SetString("msgType", "error");
                        HttpContext.Session.SetString("msgTitle", ResourceWeb.lbNotUpdate);

BooksWebProject/Areas/Admin/Controllers/PermissionsController.cs
using Domain.Constants;
using Domin.Entity;
using Infrastructure.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using WebBook.Areas.Admin.Controllers;

namespace BooksWebProject.Areas.Admin.Controllers
{
    [Area(nameof(Admin))]
    [Authorize(Permissions.Roles.Delete)]
    public class PermissionsController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public PermissionsController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Index(string roleId)
        {
            var model = new PermissionViewModel();
            var allPermissionList = Permissions.PermissionsList();
           var allPermissionIen = allPermissionList.Select(x=>new RoleClaimsViewModel {Value=x });
           var allPermissions= allPermissionIen.ToList();    
            var role = await _roleManager.FindByIdAsync(roleId);
            model.RoleId = roleId;
            var claims = await _roleManager.GetClaimsAsync(role);
            var allClaimValues = allPermissions.Select(a => a.Value).ToList();
            var roleClaimValues = claims.Select(a => a.Value).ToList();
            var authorizedClaims = allClaimValues.Intersect(roleClaimValues).ToList();
            foreach (var permission in allPermissions)
            {
                if (authorizedClaims.Any(a => a == permission.Value))
                {
                    permission.Selected = true;
                }
            }
            model.RoleClaims = allPermissions;
            model.RoleId=roleId;
            model.RoleName = role.Name;
            return View(model);
            //var role =await _roleManager.FindByIdAsync(roleId);
            //var claims =await _roleManager.GetClaimsAsync(role);
            //var allPermissions = Permissions.PermissionsList();
            //var x = allPermissions.Select(x => new RoleClaimsViewModel { Value = x }).ToList();
            //return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(PermissionViewModel model)
        {
            var role = await _roleManager.FindByIdAsync(model.RoleId);
            var claims=await _roleManager.GetClaimsAsync(role);
            foreach (var claim in claims)
            {
               await _roleManager.RemoveClaimAsync(role, claim);
            }
            var selectedClaims = model.RoleClaims.Where(c => c.Selected).ToList();

            foreach (var claim in selectedClaims)
            {
                await _roleManager.AddClaimAsync(role, new Claim(Helper.Permission,claim.Value));
            }
            return RedirectToAction("Roles", nameof(AccountsController));
        }
    }
}

BooksWebProject/Areas/Admin/Views/Accounts/Login.cshtml
@model LoginViewModel
@{ 
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Admin/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/Admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Admin/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="../../index2.html"><b>Admin</b>LTE</a>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Sign in to start your session</p>
                
                <form asp-controller="Accounts" asp-action="Login" method="post">
                    @if (ViewBag.errorMessge==false){
                        <span class="aler alert-danger w-100">@ResourceWeb.lbMsgErrorLogin</span>
                    }
                    <div class="input-group mb-3">
                        <input type="email" class="form-control" asp-for="Email" placeholder="Email">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>

                    <div class="input-group mb-3">
                        <input type="password" asp-for="Password" class="form-control" placeholder="Password">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-8">
                            <div class="icheck-primary">
                                <input type="checkbox" asp-for="RememberMe" id="remember">
                                <label for="remember">
                                    Remember Me
                                </label>
                            </div>
                        </div>
                        <!-- /.col -->
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                        </div>
                        <!-- /.col -->
                    </div>
                </form>

                <div class="social-auth-links text-center mb-3">
                    <p>- OR -</p>
                    <a href="#" class="btn btn-block btn-primary">
                        <i class="fab fa-facebook mr-2"></i> Sign in using Facebook
                    </a>
                    <a href="#" class="btn btn-block btn-danger">
                        <i class="fab fa-google-plus mr-2"></i> Sign in using Google+
                    </a>
                </div>
                <!-- /.social-auth-links -->

                <p class="mb-1">
                    <a href="#">I forgot my password</a>
                </p>
                <p class="mb-0">
                    <a href="register.html" class="text-center">Register a new membership</a>
                </p>
            </div>
            <!-- /.login-card-body -->
        </div>
    </div>
    <!-- /.login-box -->
    <!-- jQuery -->
    <script src="~/Admin/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>
</html>

BooksWebProject/Areas/Admin/Views/Accounts/Roles.cshtml
@model RolesViewModel
@{
    ViewData["Title"] = "Roles";
}
<div class="wrapper">
    <!--Content-Header-->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">@ResourceWeb.lbRoleUser</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/Admin/Home/Index">@ResourceWeb.lbHomePage</a></li>
                        <li class="breadcrumb-item active">@ResourceWeb.lbManageBook</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
        <!--End Content-Header-->
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header d-flex align-items-center justify-content-start">
                            <h3 class="card-title" style="margin-left:20px">@ResourceWeb.lbRoleUser</h3>
                            <div class="card-tools">
                                <!-- Button trigger modal -->
                                <button type="button" style="margin-top:-5px"
                                    class="btn btn-outline-primary rounded-pill" data-bs-toggle="modal" data-bs-target="#exampleModal" onclick="Reset()">
                                @ResourceWeb.lbbtnSaveNewRole
                                </button>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="tableRole" class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <td>@ResourceWeb.lbNameRole</td>
                                        <td>@ResourceWeb.lbEvents</td>

                                    </tr>
                                </thead>
                            <tbody>
                                @foreach (var item in Model.Roles)
                                {
                                    <tr>
                                        <td>
                                            @switch (@item.Name)
                                            {
                                                
                                                case "SupperAdmin":
                                                    <span class="badge badge-danger" style="width:250px; height:25px">@item.Name</span>
                                                    break;
                                                    
                                                case "Admin":
                                                <span class="badge badge-success" style="width:250px; height:25px">@item.Name</span>
                                                break;
                                                
                                                default:
                                                    <span class="badge badge-warning" style="width:250px; height:25px">@item.Name</span>
                                                    break;
                                            }
                                        </td>
                                        <td>
                                            <input type="button" class="btn btn-info btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal" onclick="Edit('@item.Id','@item.Name')" value="@ResourceWeb.lbbtnEdit" />|
                                            <input type="button" class="btn btn-danger btn-sm" onclick="Delete('@item.Id')" value="@ResourceWeb.lbbtnDelete" />
                                            <a asp-action="Index" asp-controller="Permissions" asp-route-roleId="@item.Id" class="btn btn-danger btn-sm">الصلاحيات</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>



    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog card card-success card-outline">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="title">@ResourceWeb.lbbtnSaveNewRole</h5>
                    <a href="#" class="btn-close" data-bs-dismiss="modal" aria-label="Close">x</a>
                </div>
                <div class="modal-body">
                <form asp-action="Roles" asp-controller="Accounts" method="post"
                enctype="multipart/form-data">
                    <input asp-for="NewRole.RoleId" type="hidden" id="roleId"/>

                    <div class="form-group">
                        <label asp-for="NewRole.RoleName" class="control-labal">@ResourceWeb.lbNameRole</label>
                        <input asp-for="NewRole.RoleName" type="text" class="form-control" id="roleName"/>
                        <span asp-validation-for="NewRole.RoleName" class="text-danger"></span>
                    </div> 
                    <div class="modal-footer-rtl">
                        <input type="submit" class="btn btn-primary" id="btnSubmit" value="@ResourceWeb.lbbtnSave"/>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  </div>
                    </form>
                </div>

            </div>
        </div>
    </div>

    @section Scripts{


    @if (!string.IsNullOrEmpty(Context.Session.GetString("msgType")))
        {
        if (Context.Session.GetString(Helper.MsgType) == "seccess")
            {
                <script>

            Swal.fire({
                    title: '@Context.Session.GetString("msgTitle")',
                    text: '@Html.Raw(@Context.Session.GetString("msg"))',
                    confirmButtonText: '@ResourceWeb.lbOk',
                icon: 'success'
            });
                </script>

            }
            else
            {
                <script>

             Swal.fire({
                    title: '@Context.Session.GetString("msgTitle")',
                    text: '@Html.Raw(@Context.Session.GetString("msg"))',
                    confirmButtonText: '@ResourceWeb.lbOk',
                 icon: 'error'
             });
                </script>
            }
        Context.Session.SetString("msgType", "");
        }

        <script src="~/Modules/Roles.js"></script>


        //
        <script>

        

        let lbTitleEdit = '@Html.Raw(ResourceWeb.lbTitleEdit)';
        let lbEdit = '@Html.Raw(ResourceWeb.lbEdit)';
        let lbAddNewRole = '@Html.Raw(ResourceWeb.lbAddNewRole)';
        let lbbtnSave = '@Html.Raw(ResourceWeb.lbbtnSave)';

        let lbTitleMsgDelete = '@Html.Raw(ResourceWeb.lbbtnSave)'; 
        let lbTextMsgDelete = '@Html.Raw(ResourceWeb.lbTextMsgDelete)';
        let lbconfirmButtonText = '@Html.Raw(ResourceWeb.lbconfirmButtonText)';
        let lbcancelButtonText = '@Html.Raw(ResourceWeb.lbcancelButtonText)';

        let lbTitleDeletedOk = '@Html.Raw(ResourceWeb.lbTitleDeletedOk)';
        let lbMsgDeletedOkRole = '@Html.Raw(ResourceWeb.lbMsgDeletedOkRole)';
        let lbSuccess = '@Html.Raw(Helper.Success)';
        
        </script>
    }